### ISSUE TITLE
Doesn't log in to plex from homey

### ISSUE THREAD

**Issue by iWelna** [denniedegroot/com.plex.notify#1]
Hello,

I have at my home  2 plex servers:

1. Nvidia shield 
2. My pc for some short clips

I have tried to setup the app on my homey, but when i check authorized devices at plex i don't see  Homey.

Maybe i do sth wrong with setup in Homey. Below is the pic of my settings.  Any help would be great.

![Screenshot_20200629-191826](https://user-images.githubusercontent.com/60554533/86036169-c50daa80-ba3d-11ea-9c44-96349b980474.jpg)

**Comment by denniedegroot** [comment]
Have you tested a flow card? The checkbox is for ssl communication, you can try to test with it unchecked.

**Comment by iWelna** [comment]
Ye, flows doesnt work at all, also in plex settings i don't see Homey logged into it.

**Comment by iWelna** [comment]
Maybe i do sth wrong with the flows hmm.  I wanted make sth like:

Plex is playing sth  -> turn off Hue
Plex is paused/stopped .> turn on Hue

**Comment by denniedegroot** [comment]
The flow is fine. Can you send me a diagnostics report, this can be done from within the Homey app -> apps -> Plex app.

**Comment by iWelna** [comment]
Here You go:   a6c09791-5d87-4e91-a642-f692da7e5808

**Comment by iWelna** [comment]
Got it working ><, had to put username with @ not just my login. Btw there is a way to make flow like:

When plex is playing and   server IP x.x.x.x and on user xxx  then do sth ?

Atm did sth like this, with plex server IP seems to work but my logged  username doesnt work on which i play the movie.

![image](https://user-images.githubusercontent.com/60554533/86829127-54e1d300-c094-11ea-8923-fbb0d703e30b.png)

**Comment by denniedegroot** [comment]
Yes use the ‘user’ tag in a logic compare card from the ‘Plex starts playong’ card.

**Comment by iWelna** [comment]
Thanks i'll test it out today, btw thanks for help, great APP.

**Comment by iWelna** [comment]
Everything works with user, btw there is some delay when APP tries to reconnect to plex server? 
Atm i've got flows which turns my Nvidia shield for the Night or when any of TV,aplituners is turned On, then it switches Nvidia ON. Had to restart App manualy today to get it to work.

**Comment by denniedegroot** [comment]
There shouldn't be a big delay. Unfortunately I cannot update the app anymore, for a explanation see #2.
